### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by yuyuyuyuyuty** [ZhoubinXM/VAD#1]
I saw your problem in the closed VAD problem：
Thank you very much for the valuable work of your team, I found out when I reproduced your code, since I couldn't open the URL of the train and val pkl files, I generated the corresponding pkl files through the data converter, but when I trained, a series of shapely/set_operations.py:133: RuntimeWarning: invalid value encountered in intersection return lib.intersection(a, b, **kwargs), and then the training program terminates, here is my training log:
[file.txt.zip](https://github.com/hustvl/VAD/files/12554765/file.txt.zip)
Looking forward to hearing from you!

I have the same problem as you. Have you solved the problem? Can you tell me where the problem is? thank you.

**Comment by ZhoubinXM** [comment]
> I saw your problem in the closed VAD problem： Thank you very much for the valuable work of your team, I found out when I reproduced your code, since I couldn't open the URL of the train and val pkl files, I generated the corresponding pkl files through the data converter, but when I trained, a series of shapely/set_operations.py:133: RuntimeWarning: invalid value encountered in intersection return lib.intersection(a, b, **kwargs), and then the training program terminates, here is my training log: [file.txt.zip](https://github.com/hustvl/VAD/files/12554765/file.txt.zip) Looking forward to hearing from you!
> 
> I have the same problem as you. Have you solved the problem? Can you tell me where the problem is? thank you.

Hello，reinstall `shapely` might solve this error.

**Comment by yuyuyuyuyuty** [comment]
Thank you for your response! I tried the solution you provided, and it indeed resolved my issue. I greatly appreciate your assistance!

**Comment by yuyuyuyuyuty** [comment]
I'm sorry, I just saw the email now. Thank you very much for your answer.
According to your reply, I have solved the problem, thank you very much
周彬 ***@***.***> 于2023年12月14日周四 14:56写道：
